(defun somaMult (num1 num2 num3)
  (format t "~%A soma dos números ~d e ~d" num2 num3)
  (if(/= num1 (+ num2 num3))
    (format t " não")
  )
  (format t " é igual a ~d" num1)
)

(print "Digite o primeiro número: ")
(setq num1 (read))
(print "Digite o segundo número: ")
(setq num2 (read))
(print "Digite o terceiro número: ")
(setq num3 (read))
(somaMult num1 num2 num3)
